# Generated by Django 4.0.4 on 2022-05-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Activity',
            new_name='ProductActivity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='product_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(through='products.ProductActivity', to='products.product'),
        ),
    ]
